import { css } from '@emotion/css'
import { useSession } from 'next-auth/react'
import { signOut } from '../lib/utils'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { ReactNode, useEffect, useState } from 'react'
import NZXTLogo from './NZXTLogo'

const styles = {
  background: css`
    position: absolute;
    z-index: -1;
    opacity: 0.1;
    height: 100%;
    width: 100%;
    background-blend-mode: multiply;
    background: url('/home_background.jpg');
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center;
    background-attachment: fixed;
  `,
  container: css`
    height: 100vh;
    width: 100vw;
    user-select: none;
  `,
  nav: css`
    display: flex;
    position: relative;
    width: 100%;
    height: 50px;
    justify-content: space-between;
    align-items: center;
    border-bottom: 1px solid #1e1e1f;
  `,
  logo: css`
    height: auto;
    height: 53px;
    width: 100px;
    margin: 0 20px;
    cursor: pointer;
    color: #ffffff;
    transition: ease 0.1s;

    &:hover {
      color: #8a00fc;
    }
  `,
  signOut: css`
    margin: 0 20px;
    color: white;
    transition: ease 0.1s;

    &:hover {
      color: #8a00fc;
      cursor: pointer;
    }
  `,
}

const Layout = ({ children }: { children: ReactNode }) => {
  const [loading, setLoading] = useState(true)
  const router = useRouter()
  const { data: session } = useSession()
  const { kraken } = router.query

  const showNav = !router.pathname.includes('/album')

  useEffect(() => {
    setLoading(false)
  }, [])

  useEffect(() => {
    if (session?.error === 'RefreshAccessTokenError') {
      signOut()
    }
  }, [session])

  if (loading) return <></>

  return (
    <>
      <Head>
        <title>Photo Slideshow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {!kraken && !session && (router.pathname === '/' || router.pathname === '/signin') && (
          <div className={styles.background} />
        )}
        {!kraken && showNav && (
          <div className={styles.nav}>
            <div onClick={() => router.push('/')}>
              <NZXTLogo className={styles.logo} />
            </div>
            {session && (
              <>
                <div />
                <Link className={styles.signOut} onClick={() => signOut()} href="/api/auth/signin">
                  {'Sign Out'}
                </Link>
              </>
            )}
          </div>
        )}
        {children}
      </div>
    </>
  )
}

export default Layout
